# Generated by Django 3.2.4 on 2021-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('capital_provincial', models.CharField(max_length=30)),
                ('poblacion', models.IntegerField()),
            ],
        ),
    ]
