# Generated by Django 3.2.4 on 2021-06-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provincia',
            new_name='Provincias',
        ),
    ]
