# Generated by Django 3.2.4 on 2021-06-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_rename_provincia_provincias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provincias',
            new_name='Provincia',
        ),
    ]
